# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8062426da1874d1a01c64a65bddc3bcdf99eca9cf1bace61d7af0629c650bb12f2dca062f5f9be9ee8988ac0fdbdc2fe38431dc9f0a71b24c4c7a3008af8848e

test:
  secret_key_base: 749b162f6507153e85ccea52004f9ce0afe291a31e6548f51f286a735a8fc158e8eb7d8405db6ae9c45422cec64a339162cf55799661257104ca6a3b999dbfe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
